Update urdf.py to have tag on joint and link reflections
ros/urdf_parser_py pull request #18
Opened 2017-07-11 15:26 UTC by willcbaker

Enables user to use to_xml() function on joints and links

2017-07-12 13:12 UTC, clalancette commented
The concept seems OK to me; I don't think this will break any backwards compatibility, either.  However, if we are going to go down the route of adding tags, I'd rather we do it for all of the reflections in urdf.py.  @sloretz , thoughts?

2017-07-12 14:59 UTC, sloretz requested changes
@willcbaker Adding the tag is a great idea. Just a tiny formatting change is needed.

@clalancette yeah I agree. If one tag supports a feature, they all should. @willcbaker would you mind adding tags to the ones which don't already have it?

2017-07-12 14:59 UTC, sloretz commented on src/urdf_parser_py/urdf.py
> +xmlr.reflect(Joint, tag = 'joint', params = [
nitpick, no spaces next to the equals sign in keyword argument.

2017-07-12 14:59 UTC, sloretz commented on src/urdf_parser_py/urdf.py
> +xmlr.reflect(Link, tag = 'link', params = [
Same, There should be no spaces next to equal sign. Of course, nothing else in this module follows pep 8, but it'd be nice to start.

2017-07-26 17:20 UTC, clalancette commented
@willcbaker Given that this seems to be subsumed by #20, closing this.  If I'm mistaken, feel free to reopen.

2017-07-26 17:20 UTC, closed without merging